# configuration for "master" branch
-
  branches:
      only:
        - master
  version: 1.0.0.{build}
  image: Visual Studio 2017 RC
  environment:
    ANDROID_HOME: "C:\\android-sdk-windows"
    NUGET_SOURCE: https://www.nuget.org/api/v2/package
    NUGET_APIKEY:
      secure: sHlNV/4D92Gjf6il/D/SfoXNp43TzZMMT4Jd/7OjtLL56maSe006Y2I5W4C8/U/Y
  init:
  - cd \
  - appveyor DownloadFile http://dl.google.com/android/android-sdk_r24.4.1-windows.zip
  - 7z x android-sdk_r24.4.1-windows.zip > nul
  - cd "C:\projects\Xamarin-CrossDownloadManager"
  install: 
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t tools
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t platform-tools
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t build-tools-24.0.2
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t android-24
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t extra-google-m2repository
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t extra-android-m2repository
  build_script:
  - ps: .\build.ps1
  test: off
  # configuration for "master" branch
-
  branches:
      only:
        - develop
  version: 1.0.0.{build}
  image: Visual Studio 2017 RC
  environment:
    ANDROID_HOME: "C:\\android-sdk-windows"
    NUGET_SOURCE: https://www.myget.org/F/simonsimcity/api/v2/package
    NUGET_APIKEY:
      secure: RnJPCNw3MFXAN9Ro8pEiMj5517Zi+3QW2zMkr2AnsF9I0rI8OdM77N9Db3c070J0
  init:
  - cd \
  - appveyor DownloadFile http://dl.google.com/android/android-sdk_r24.4.1-windows.zip
  - 7z x android-sdk_r24.4.1-windows.zip > nul
  - cd "C:\projects\Xamarin-CrossDownloadManager"
  install: 
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t tools
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t platform-tools
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t build-tools-24.0.2
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t android-24
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t extra-google-m2repository
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t extra-android-m2repository
  build_script:
  - ps: .\build.ps1
  test: off
